sudo: false
language: android

android:
    components:
        - build-tools-21.1.2
        - android-23
        - extra-android-m2repository
    licenses:
        - '.+'

# Don't send email.
notifications:
    email:
        on_success: never
        on_failure: never

# Set up.
before_install:
    # Grant Gradle Wrapper execute permission.
    - chmod +x gradlew

script: ./gradlew testDebugUnitTestCoverage

after_success: ./gradlew coveralls
