language: android

android:
    components:
        - build-tools-21.1.2
        - android-23
        - extra-android-m2repository
    licenses:
        - '.+'
        
# Don't send email.
notifications:
  email:
    on_success: never
    on_failure: never

script: ./gradlew testDebugUnitTestCoverage
